/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'project-details-component': ProjectDetailsComponent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'project-details-component': ProjectDetailsComponentSelect<false> | ProjectDetailsComponentSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  /**
   * Cloudinary URL - use this in your frontend
   */
  cloudinary_url?: string | null;
  public_id?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-details-component".
 */
export interface ProjectDetailsComponent {
  id: string;
  componentName: string;
  /**
   * Used in URL: /projects/your-slug-here
   */
  slug: string;
  heroSection: {
    show?: boolean | null;
    className?: string | null;
    backgroundColor?: string | null;
    padding?: {
      top?: string | null;
      bottom?: string | null;
      left?: string | null;
      right?: string | null;
    };
    titleBlock: {
      title: string;
      titleColor?: string | null;
      titleFontSize?: string | null;
      titleFontWeight?: string | null;
      titleLineHeight?: string | null;
      titleAnimation?: string | null;
      showHorizontalLine?: boolean | null;
      lineClassName?: string | null;
      lineColor?: string | null;
      lineHeight?: string | null;
      /**
       * Final width percentage (e.g., 100%)
       */
      lineAnimationWidth?: string | null;
    };
    descriptionBlock?: {
      show?: boolean | null;
      description?: string | null;
      descriptionColor?: string | null;
      descriptionFontSize?: string | null;
      descriptionLineHeight?: string | null;
      animationTransform?: string | null;
      animationOpacity?: string | null;
      animationBlur?: string | null;
    };
    button?: {
      show?: boolean | null;
      text?: string | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      icon?: (string | null) | Media;
      iconUrl?: string | null;
      iconAlt?: string | null;
      variant?: string | null;
      className?: string | null;
      backgroundColor?: string | null;
      hoverBackgroundColor?: string | null;
      textColor?: string | null;
      borderRadius?: string | null;
      padding?: string | null;
    };
    /**
     * Drag to reorder widgets (Client, Industry, Services, etc.)
     */
    widgets?:
      | {
          type: string;
          name: string;
          show?: boolean | null;
          typeColor?: string | null;
          typeFontSize?: string | null;
          nameColor?: string | null;
          nameFontSize?: string | null;
          nameFontWeight?: string | null;
          backgroundColor?: string | null;
          padding?: string | null;
          borderRadius?: string | null;
          id?: string | null;
        }[]
      | null;
    widgetsBlockStyles?: {
      backgroundColor?: string | null;
      gap?: string | null;
      marginTop?: string | null;
      animationTransform?: string | null;
      animationOpacity?: string | null;
      animationBlur?: string | null;
    };
    heroImage?: {
      show?: boolean | null;
      image?: (string | null) | Media;
      imageUrl?: string | null;
      alt?: string | null;
      responsiveImages?: {
        mobile?: (string | null) | Media;
        mobileUrl?: string | null;
      };
      sizes?: string | null;
      borderRadius?: string | null;
      boxShadow?: string | null;
      animationOpacity?: string | null;
    };
  };
  bannerImageSection?: {
    show?: boolean | null;
    className?: string | null;
    backgroundColor?: string | null;
    padding?: {
      top?: string | null;
      bottom?: string | null;
    };
    marginTop?: string | null;
    marginBottom?: string | null;
    image?: (string | null) | Media;
    imageUrl?: string | null;
    alt?: string | null;
    responsiveImages?: {
      mobile?: (string | null) | Media;
      mobileUrl?: string | null;
      tablet?: (string | null) | Media;
      tabletUrl?: string | null;
      desktop?: (string | null) | Media;
      desktopUrl?: string | null;
    };
    sizes?: string | null;
    borderRadius?: string | null;
    animationOpacity?: string | null;
    maxWidth?: string | null;
  };
  contentSection: {
    show?: boolean | null;
    className?: string | null;
    backgroundColor?: string | null;
    padding?: {
      top?: string | null;
      bottom?: string | null;
      left?: string | null;
      right?: string | null;
    };
    marginTop?: string | null;
    marginBottom?: string | null;
    richTextWrapper?: {
      className?: string | null;
      maxWidth?: string | null;
      animationTransform?: string | null;
      animationOpacity?: string | null;
      animationBlur?: string | null;
    };
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Drag to reorder sections on the page
   */
  sectionOrder?:
    | {
        section: 'hero' | 'bannerImage' | 'content';
        id?: string | null;
      }[]
    | null;
  globalStyles?: {
    /**
     * CSS max-width value (e.g., 1200px, 100%)
     */
    containerMaxWidth?: string | null;
    /**
     * CSS padding value (e.g., 20px, 1rem 2rem)
     */
    containerPadding?: string | null;
    /**
     * Spacing between sections (e.g., 60px, 4rem)
     */
    sectionSpacing?: string | null;
    /**
     * CSS font-family value
     */
    fontFamily?: string | null;
    /**
     * Primary brand color
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color
     */
    secondaryColor?: string | null;
    /**
     * Accent color for highlights
     */
    accentColor?: string | null;
    /**
     * Default text color for the page
     */
    textColor?: string | null;
    /**
     * Default color for links
     */
    linkColor?: string | null;
    /**
     * Color for links on hover
     */
    linkHoverColor?: string | null;
    /**
     * Default border radius for elements
     */
    borderRadius?: string | null;
    /**
     * Default box shadow for elements
     */
    boxShadow?: string | null;
  };
  typographySettings?: {
    h1FontSize?: string | null;
    h1Color?: string | null;
    h1FontWeight?: string | null;
    h1LineHeight?: string | null;
    h1MarginBottom?: string | null;
    h2FontSize?: string | null;
    h2Color?: string | null;
    h2FontWeight?: string | null;
    h2LineHeight?: string | null;
    h2MarginBottom?: string | null;
    h3FontSize?: string | null;
    h3Color?: string | null;
    h3FontWeight?: string | null;
    h3LineHeight?: string | null;
    h3MarginBottom?: string | null;
    h4FontSize?: string | null;
    h4Color?: string | null;
    h4FontWeight?: string | null;
    bodyFontSize?: string | null;
    bodyLineHeight?: string | null;
    paragraphSpacing?: string | null;
    /**
     * CSS list-style-type (e.g., disc, circle, square)
     */
    listStyleType?: string | null;
    listMarginLeft?: string | null;
    listItemSpacing?: string | null;
    strongFontWeight?: string | null;
  };
  layoutSettings?: {
    /**
     * CSS grid columns for hero (e.g., 1fr 1fr)
     */
    heroGridColumns?: string | null;
    heroGridGap?: string | null;
    /**
     * Max width for content section
     */
    contentMaxWidth?: string | null;
    /**
     * Gap between columns (e.g., 30px, 2rem)
     */
    columnGap?: string | null;
    /**
     * Gap between rows (e.g., 20px, 1.5rem)
     */
    rowGap?: string | null;
    imageObjectFit?: ('cover' | 'contain' | 'fill' | 'none') | null;
    /**
     * CSS background-position value
     */
    imagePosition?: string | null;
    widgetsLayout?: ('flex-row' | 'flex-column' | 'grid') | null;
  };
  animationSettings?: {
    enableAnimations?: boolean | null;
    /**
     * Duration for fade in animations (e.g., 1s, 2s)
     */
    fadeInDuration?: string | null;
    /**
     * Delay before fade in starts (e.g., 0.2s)
     */
    fadeInDelay?: string | null;
    /**
     * Duration for slide animations
     */
    slideInDuration?: string | null;
    /**
     * Distance elements slide from (e.g., 50px)
     */
    slideInDistance?: string | null;
    /**
     * Duration for hover effects
     */
    hoverTransitionDuration?: string | null;
    /**
     * CSS easing function
     */
    animationEasing?: string | null;
    /**
     * Enable scroll-triggered animations
     */
    enableScrollAnimations?: boolean | null;
    /**
     * Distance from viewport to trigger animation (px)
     */
    scrollOffset?: string | null;
    /**
     * Duration for horizontal line animation
     */
    lineAnimationDuration?: string | null;
    lineAnimationDelay?: string | null;
    /**
     * Scale factor on button hover (e.g., 1.05)
     */
    buttonHoverScale?: string | null;
  };
  richTextStyles?: {
    figureMaxWidth?: string | null;
    figureMargin?: string | null;
    imageMargin?: string | null;
    imageBorderRadius?: string | null;
    /**
     * Padding-bottom percentage for video containers
     */
    videoAspectRatio?: string | null;
    blockquoteStyle?: {
      borderLeft?: string | null;
      padding?: string | null;
      fontStyle?: string | null;
      backgroundColor?: string | null;
    };
    codeBlockStyle?: {
      backgroundColor?: string | null;
      padding?: string | null;
      borderRadius?: string | null;
      fontFamily?: string | null;
    };
  };
  mobileSettings?: {
    /**
     * Screen width for mobile (e.g., 767px)
     */
    mobileBreakpoint?: string | null;
    /**
     * Screen width for tablet (e.g., 991px)
     */
    tabletBreakpoint?: string | null;
    /**
     * Font size adjustment for titles on mobile
     */
    mobileTitleFontSize?: string | null;
    mobileDescriptionFontSize?: string | null;
    /**
     * Percentage adjustment for mobile fonts (e.g., 90%)
     */
    mobileFontSizeAdjustment?: string | null;
    /**
     * Percentage adjustment for mobile spacing
     */
    mobileSpacingAdjustment?: string | null;
    /**
     * Automatically stack sections vertically on mobile devices
     */
    mobileStackSections?: boolean | null;
    mobileHeroLayout?: ('stack-below' | 'stack-above' | 'single-column') | null;
    mobileWidgetsLayout?: ('stack' | 'grid-2' | 'scroll') | null;
    mobileCounterLayout?: ('stack' | 'grid-2x2') | null;
    /**
     * List of element classes to hide on mobile
     */
    mobileHideElements?:
      | {
          className?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seoSettings?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    ogImageUrl?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords?: string | null;
    canonicalUrl?: string | null;
    robots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    /**
     * Add schema.org structured data in JSON-LD format
     */
    structuredData?: string | null;
    breadcrumbsEnabled?: boolean | null;
  };
  accessibilitySettings?: {
    skipToContent?: boolean | null;
    skipToContentTarget?: string | null;
    ariaLabelsEnabled?: boolean | null;
    altTextRequired?: boolean | null;
    /**
     * Color for focus outlines (accessibility)
     */
    focusVisibleColor?: string | null;
    focusVisibleWidth?: string | null;
    focusVisibleStyle?: ('solid' | 'dashed' | 'dotted') | null;
    contrastMode?: ('normal' | 'high' | 'very-high') | null;
    keyboardNavigationEnabled?: boolean | null;
  };
  performanceSettings?: {
    lazyLoadImages?: boolean | null;
    imageOptimization?: boolean | null;
    /**
     * Compression quality (1-100)
     */
    imageQuality?: string | null;
    imageFormat?: ('auto' | 'webp' | 'avif' | 'jpeg' | 'png') | null;
    /**
     * Comma-separated widths for responsive images
     */
    responsiveImageSizes?: string | null;
    /**
     * Preload hero and above-the-fold images
     */
    preloadCriticalImages?: boolean | null;
    minifyCSS?: boolean | null;
    minifyJS?: boolean | null;
    enableCDN?: boolean | null;
    /**
     * Base URL for CDN
     */
    cdnUrl?: string | null;
  };
  advancedSettings?: {
    /**
     * Add custom CSS styles for this component
     */
    customCSS?: string | null;
    /**
     * Add custom JavaScript code for this component
     */
    customJS?: string | null;
    /**
     * Add custom data attributes to sections
     */
    dataAttributes?:
      | {
          /**
           * e.g., data-tracking-id
           */
          attribute?: string | null;
          value?: string | null;
          targetSection?: ('hero' | 'bannerImage' | 'content' | 'counter') | null;
          id?: string | null;
        }[]
      | null;
    enableCaching?: boolean | null;
    cacheTimeout?: string | null;
  };
  integrationSettings?: {
    /**
     * GA tracking ID for this component
     */
    googleAnalyticsId?: string | null;
    facebookPixelId?: string | null;
    trackingEnabled?: boolean | null;
    /**
     * Define custom tracking events
     */
    trackingEvents?:
      | {
          eventName: string;
          trigger?: ('load' | 'click' | 'scroll' | 'button-click') | null;
          /**
           * CSS selector for the target element
           */
          targetElement?: string | null;
          id?: string | null;
        }[]
      | null;
    conversionTrackingEnabled?: boolean | null;
  };
  /**
   * Toggle to enable/disable this component
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'project-details-component';
        value: string | ProjectDetailsComponent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary_url?: T;
  public_id?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-details-component_select".
 */
export interface ProjectDetailsComponentSelect<T extends boolean = true> {
  componentName?: T;
  slug?: T;
  heroSection?:
    | T
    | {
        show?: T;
        className?: T;
        backgroundColor?: T;
        padding?:
          | T
          | {
              top?: T;
              bottom?: T;
              left?: T;
              right?: T;
            };
        titleBlock?:
          | T
          | {
              title?: T;
              titleColor?: T;
              titleFontSize?: T;
              titleFontWeight?: T;
              titleLineHeight?: T;
              titleAnimation?: T;
              showHorizontalLine?: T;
              lineClassName?: T;
              lineColor?: T;
              lineHeight?: T;
              lineAnimationWidth?: T;
            };
        descriptionBlock?:
          | T
          | {
              show?: T;
              description?: T;
              descriptionColor?: T;
              descriptionFontSize?: T;
              descriptionLineHeight?: T;
              animationTransform?: T;
              animationOpacity?: T;
              animationBlur?: T;
            };
        button?:
          | T
          | {
              show?: T;
              text?: T;
              url?: T;
              openInNewTab?: T;
              icon?: T;
              iconUrl?: T;
              iconAlt?: T;
              variant?: T;
              className?: T;
              backgroundColor?: T;
              hoverBackgroundColor?: T;
              textColor?: T;
              borderRadius?: T;
              padding?: T;
            };
        widgets?:
          | T
          | {
              type?: T;
              name?: T;
              show?: T;
              typeColor?: T;
              typeFontSize?: T;
              nameColor?: T;
              nameFontSize?: T;
              nameFontWeight?: T;
              backgroundColor?: T;
              padding?: T;
              borderRadius?: T;
              id?: T;
            };
        widgetsBlockStyles?:
          | T
          | {
              backgroundColor?: T;
              gap?: T;
              marginTop?: T;
              animationTransform?: T;
              animationOpacity?: T;
              animationBlur?: T;
            };
        heroImage?:
          | T
          | {
              show?: T;
              image?: T;
              imageUrl?: T;
              alt?: T;
              responsiveImages?:
                | T
                | {
                    mobile?: T;
                    mobileUrl?: T;
                  };
              sizes?: T;
              borderRadius?: T;
              boxShadow?: T;
              animationOpacity?: T;
            };
      };
  bannerImageSection?:
    | T
    | {
        show?: T;
        className?: T;
        backgroundColor?: T;
        padding?:
          | T
          | {
              top?: T;
              bottom?: T;
            };
        marginTop?: T;
        marginBottom?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        responsiveImages?:
          | T
          | {
              mobile?: T;
              mobileUrl?: T;
              tablet?: T;
              tabletUrl?: T;
              desktop?: T;
              desktopUrl?: T;
            };
        sizes?: T;
        borderRadius?: T;
        animationOpacity?: T;
        maxWidth?: T;
      };
  contentSection?:
    | T
    | {
        show?: T;
        className?: T;
        backgroundColor?: T;
        padding?:
          | T
          | {
              top?: T;
              bottom?: T;
              left?: T;
              right?: T;
            };
        marginTop?: T;
        marginBottom?: T;
        richTextWrapper?:
          | T
          | {
              className?: T;
              maxWidth?: T;
              animationTransform?: T;
              animationOpacity?: T;
              animationBlur?: T;
            };
        content?: T;
      };
  sectionOrder?:
    | T
    | {
        section?: T;
        id?: T;
      };
  globalStyles?:
    | T
    | {
        containerMaxWidth?: T;
        containerPadding?: T;
        sectionSpacing?: T;
        fontFamily?: T;
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        textColor?: T;
        linkColor?: T;
        linkHoverColor?: T;
        borderRadius?: T;
        boxShadow?: T;
      };
  typographySettings?:
    | T
    | {
        h1FontSize?: T;
        h1Color?: T;
        h1FontWeight?: T;
        h1LineHeight?: T;
        h1MarginBottom?: T;
        h2FontSize?: T;
        h2Color?: T;
        h2FontWeight?: T;
        h2LineHeight?: T;
        h2MarginBottom?: T;
        h3FontSize?: T;
        h3Color?: T;
        h3FontWeight?: T;
        h3LineHeight?: T;
        h3MarginBottom?: T;
        h4FontSize?: T;
        h4Color?: T;
        h4FontWeight?: T;
        bodyFontSize?: T;
        bodyLineHeight?: T;
        paragraphSpacing?: T;
        listStyleType?: T;
        listMarginLeft?: T;
        listItemSpacing?: T;
        strongFontWeight?: T;
      };
  layoutSettings?:
    | T
    | {
        heroGridColumns?: T;
        heroGridGap?: T;
        contentMaxWidth?: T;
        columnGap?: T;
        rowGap?: T;
        imageObjectFit?: T;
        imagePosition?: T;
        widgetsLayout?: T;
      };
  animationSettings?:
    | T
    | {
        enableAnimations?: T;
        fadeInDuration?: T;
        fadeInDelay?: T;
        slideInDuration?: T;
        slideInDistance?: T;
        hoverTransitionDuration?: T;
        animationEasing?: T;
        enableScrollAnimations?: T;
        scrollOffset?: T;
        lineAnimationDuration?: T;
        lineAnimationDelay?: T;
        buttonHoverScale?: T;
      };
  richTextStyles?:
    | T
    | {
        figureMaxWidth?: T;
        figureMargin?: T;
        imageMargin?: T;
        imageBorderRadius?: T;
        videoAspectRatio?: T;
        blockquoteStyle?:
          | T
          | {
              borderLeft?: T;
              padding?: T;
              fontStyle?: T;
              backgroundColor?: T;
            };
        codeBlockStyle?:
          | T
          | {
              backgroundColor?: T;
              padding?: T;
              borderRadius?: T;
              fontFamily?: T;
            };
      };
  mobileSettings?:
    | T
    | {
        mobileBreakpoint?: T;
        tabletBreakpoint?: T;
        mobileTitleFontSize?: T;
        mobileDescriptionFontSize?: T;
        mobileFontSizeAdjustment?: T;
        mobileSpacingAdjustment?: T;
        mobileStackSections?: T;
        mobileHeroLayout?: T;
        mobileWidgetsLayout?: T;
        mobileCounterLayout?: T;
        mobileHideElements?:
          | T
          | {
              className?: T;
              id?: T;
            };
      };
  seoSettings?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        ogImageUrl?: T;
        keywords?: T;
        canonicalUrl?: T;
        robots?: T;
        structuredData?: T;
        breadcrumbsEnabled?: T;
      };
  accessibilitySettings?:
    | T
    | {
        skipToContent?: T;
        skipToContentTarget?: T;
        ariaLabelsEnabled?: T;
        altTextRequired?: T;
        focusVisibleColor?: T;
        focusVisibleWidth?: T;
        focusVisibleStyle?: T;
        contrastMode?: T;
        keyboardNavigationEnabled?: T;
      };
  performanceSettings?:
    | T
    | {
        lazyLoadImages?: T;
        imageOptimization?: T;
        imageQuality?: T;
        imageFormat?: T;
        responsiveImageSizes?: T;
        preloadCriticalImages?: T;
        minifyCSS?: T;
        minifyJS?: T;
        enableCDN?: T;
        cdnUrl?: T;
      };
  advancedSettings?:
    | T
    | {
        customCSS?: T;
        customJS?: T;
        dataAttributes?:
          | T
          | {
              attribute?: T;
              value?: T;
              targetSection?: T;
              id?: T;
            };
        enableCaching?: T;
        cacheTimeout?: T;
      };
  integrationSettings?:
    | T
    | {
        googleAnalyticsId?: T;
        facebookPixelId?: T;
        trackingEnabled?: T;
        trackingEvents?:
          | T
          | {
              eventName?: T;
              trigger?: T;
              targetElement?: T;
              id?: T;
            };
        conversionTrackingEnabled?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}